[package]
name = "kos-exec-ffi"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Jun-young Han <jyhan@katech.re.kr>"]
repository = "https://github.com/KATECH-JYHAN/kos-exec"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "kos_exec"

[dependencies]
kos-exec = { path = "../kos-exec" }
